### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kotoroshinoto** [jeremysalwen/TerminalWx#1]
src/terminalwx.cpp: In member function 'virtual void TerminalWx::DisplayChars(co
nst wxString&)':
src/terminalwx.cpp:63:12: error: 'class TerminalWx' has no member named 'QueueEv
ent'

**Comment by jeremysalwen** [comment]
What version of wxWidgets are you using? You'll need version 2.9 or later, and I suspect this is the problem.

**Comment by Wolf-SO** [comment]
Would you say that this issue is fixed or invalid by now?

**Comment by jeremysalwen** [comment]
I would say it is likely caused by someone attempting to compile vs a wxwidgets before 2.9.  At the time I posted that comment I double checked that the latest master compiled for me.

**Comment by kotoroshinoto** [comment]
its been far too long, but I suspect I probably was on the wrong version
